services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    stdin_open: true
    tty: true
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
    env_file: .env
    restart: unless-stopped
